name: Deploy to DreamHost

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.19.0"

      - name: Verify Node Version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Build Astro Site
        run: npm run build

      - name: Verify Build Output
        run: |
          echo "Verifying build output..."
          ls -la dist/
          ls -la dist/client/
          echo "Checking for critical files..."
          if [ ! -f "dist/start.js" ]; then
            echo "Error: dist/start.js is missing!"
            exit 1
          fi
          if [ ! -f "dist/.htaccess" ]; then
            echo "Error: dist/.htaccess is missing!"
            exit 1
          fi
          if [ ! -d "dist/client/_astro" ]; then
            echo "Error: dist/client/_astro directory is missing!"
            exit 1
          fi
          echo "Build verification completed successfully."
          
      # We'll use a different approach for backups
      # The restore-site.js script can be used for manual restoration if needed

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: ${{ secrets.FTP_REMOTE_PATH }}
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
          state-name: .ftp-deploy-sync-state.json
          log-level: verbose
